# Generated by Django 4.2 on 2023-05-01 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('post_date', models.DateTimeField(default=datetime.datetime(2023, 5, 1, 7, 13, 31, 884212))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
